apiVersion: v1
kind: Secret
metadata:
  name: drone-secrets
type: Opaque
data: 
  # echo -n sqlite3 | base64
  DATABASE_DRIVER: c3FsaXRlMw==
  # echo -n github | base64
  REMOTE_DRIVER: Z2l0aHVi
  # echo -n "https://github.com?client_id=abcd...&client_secret=def..." | base64
  REMOTE_CONFIG: aHR0cHM6Ly9naXRodWIuY29tP2NsaWVudF9pZD10lOWM0MzQyMmEdhhyNmRkOTI2NDQzJmNsaWVudF9zZWNyZXQ9OTYzMzg3ZDJhMWQ3ZmM2NjcxNWQzZDk2NGVhYzVmNDQyYzA1N2Y4ZQ==
  # echo -n "/var/lib/drone/drone.sqlite" | base64
  DATABASE_CONFIG: L3Zhci9saWIvZHJvbmUvZHJvbmUuc3FsaXRl
