apiVersion: v1
kind: Secret
metadata:
  name: drone-secrets
type: Opaque
data: 
  # your drone client ID of your OAuth Application
  # Client id: 12344... 
  # Then run: echo -n "1234..." | base64
  # then put the output here. 
  DRONE_GITHUB_CLIENT: 
  
  # your Oauth secret
  # Then run: echo -n "1234..." | base64
  # then put the output here. 
  DRONE_GITHUB_SECRET: 

  # Random Drone secret number.  Whatever you want
  # then base64 encode. This is used by cmdline client to talk
  # to drone as well
  DRONE_SECRET: 
